version: '3.8'

services:
  fish-detection:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fish-detection-system
    ports:
      - "5003:5003"
    volumes:
      - ./logs:/app/logs
      - ./static/uploads:/app/static/uploads
      - ./static/processed:/app/static/processed
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=your_development_secret_key_here # 请替换为一个强密码
    restart: unless-stopped
    networks:
      - fish-detection-network

networks:
  fish-detection-network:
    driver: bridge

volumes:
  logs:
  uploads:
  processed:
  data:
